//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [Required]

        public string MAHOADON { get; set; }
        [Required]

        public string MAKH { get; set; }
        [Required]

        public string MAGIOHANG { get; set; }
        [Required]

        public int GIATHANHTOAN { get; set; }
        [Required]

        public System.DateTime NGAYTHANHTOAN { get; set; }
        [Required]

        public int Phone { get; set; }
        [Required]

        public string Address { get; set; }
        [Required]

        public string FirstName { get; set; }
        [Required]

        public string LastName { get; set; }
        [Required]
        public int Id { get; set; }

        public Nullable<int> DiscountValue { get; set; }


    }
}
