//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coupon
    {
        [Required]
        public string MAMGGIA { get; set; }
        [Required]

        public string MANV { get; set; }


        public System.DateTime NGAYTAO { get; set; }

        [Required]

        public Nullable<int> THOIHAN { get; set; }

        [Required]

        public string THONGTINGIAMGIA { get; set; }
        [Required]
        public int GIATRIGIAMGIATOIDA { get; set; }

    }
}
