//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public string MAMGGIA { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public Nullable<int> THOIHAN { get; set; }
        public string THONGTINGIAMGIA { get; set; }
        public int GIATRIGIAMGIATOIDA { get; set; }
    }
}
