//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderStatu
    {
        [Required]
        public string MATT { get; set; }

        [Required]
        public string MAHD { get; set; }

        [Required]
        public string TRANGTHAI { get; set; }

        [Required]

        public string MANVTHEODOI { get; set; }

    }
}
