//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.CartDetails = new HashSet<CartDetail>();
        }

        [Required]

        public string MASP { get; set; }
        [Required]
        public string MALOHANG { get; set; }
        [Required]

        public string TENSANPHAM { get; set; }
        [Required]

        public string ANHSP { get; set; }
        [Required]

        public int GIATIEN { get; set; }
        [Required]

        public string THUONGHIEU { get; set; }
        [Required]

        public string MANPP { get; set; }
        [Required]

        public int SIZE { get; set; }
        [Required]

        public Nullable<System.DateTime> NGAYTRAVE { get; set; }


        public int VAT { get; set; }
        [Required]

        public string MAU { get; set; }
        [Required]

        public int SOLUONG { get; set; }
        [Required]

        public string MOTA { get; set; }
        [Required]

        public string TENNV { get; set; }
        [Required]

        public string LOAI { get; set; }
        [Required]

        public string KIEU { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual LOHANG LOHANG { get; set; }
    }
}
